alias brewu="brew update && brew upgrade --all && brew cleanup"
alias gpfwl="git push --force-with-lease && cowsay -f dragon-and-cow 'Force pushing!!!'"
alias gri="git rebase -i origin/master"
alias ls="ls -alGFh"
alias vim="mvim -v"
