tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "bat"
brew "curl"
# brew "docker", link: false
brew "fzf"
brew "git"
brew "jq"
brew "neovim"
brew "tmux"
brew "rbenv"
brew "rsync"
brew "the_silver_searcher"

# cask "atom-nightly"
# cask "brave-browser-nightly"
# cask "docker"
# cask "font-sf-mono-for-powerline"
# cask "gifcapture"
# cask "gimp"
# cask "google-chrome"
# cask "jumpcut"
# cask "sequel-ace"
# cask "sizeup"
# cask "slack"
# cask "spotify"
# cask "standard-notes"
# cask "visual-studio-code-insiders"
# cask "vlc"
# cask "zoom"
