if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ -f ~/.git-completion.bash ]; then
  source ~/.git-completion.bash
fi

if [ -f /usr/local/opt/bash-git-prompt/share/gitprompt.sh ]; then
  __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
  source /usr/local/opt/bash-git-prompt/share/gitprompt.sh
else
  export PS1="\[\033[36m\]$(gshuf -n 1 ~/dotfiles/bash/emojis.txt)\[\033[m\] \[\033[33;1m\]\w\[\033[m\]\[\033[36m\] (\$(git branch 2>/dev/null | grep '^*' | colrm 1 2))\[\033[m\] "
fi

db() {
  current_branch=`eval "git rev-parse --abbrev-ref HEAD"`

  if [ "$current_branch" == "master" ]; then
    echo "Current branch is master. Cannot delete master."
    return 0
  fi

  echo "Are you sure you want to delete branch $current_branch?"
  select yn in "Yes" "No"; do
    case $yn in
      Yes ) break;;
      No ) return 0;;
    esac
  done

  git checkout master
  git branch -D $current_branch
  git fetch --all -p
  git pull

  return 0
}

updateVimPackages() {
  current_dir=`eval "pwd"`

  cd ~/.vim/pack/packages/start

  for d in */ ; do
    cd $d
    git gc --prune=now
    git fetch --all -p
    git pull
    cd ..
  done

  cd $current_dir
}

alias ber="bundle exec rake"
alias brewu="brew update && brew upgrade && brew cleanup"
alias gd="git diff"
alias gf="git gc --prune=now && git fetch --all -p && git pull"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gpfwl="git push --force-with-lease && cowsay -r 'Force push (with lease)' | lolcatjs"
alias gri="git rebase -i origin/master"
alias gs="git status"
alias gwip="git add . && git commit -m 'WIP' && git push"
alias ls="ls -alFh"
alias proj="cd ~/Documents/Projects"
alias qf="git add . && git commit -m '.' && gri && gpfwl"
alias upd="brewu && npm i -g npm && npm update -g && pip3 install --upgrade pip setuptools wheel && updateVimPackages"
